name: publish to nuget
on:
  push:
    branches:
    - build
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        
    - name: pack
      run: dotnet pack --configuration Release