name: publish to nuget
on:
  push

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup dotnet core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.201
        
    - name: pack
      run: dotnet pack --configuration Release -o ./bin/publish