name: publish to nuget
on:
  push:
    branches:
    - build
jobs:
  build-publish:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '8.0.x'
        
    - name: pack
      run: dotnet pack --configuration Release

    - name: publish to nuget
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json