name: publish to azure
on:
  push:
    branches:
    - dev
jobs:
  build-publish:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '8.0.x'
        source-url: https://pkgs.dev.azure.com/gohopo/_packaging/dev/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_KEY }}
        
    - name: pack
      run: dotnet pack --configuration Release

    - name: publish to nuget
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key az --source "dev"