name: publish to azure
on:
  push:
    branches:
    - dev
jobs:
  build-publish:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '8.0.x'
        
    - name: pack
      run: dotnet pack --configuration Release

    - name: add azure source
      run: dotnet nuget add source https://pkgs.dev.azure.com/gohopo/_packaging/dev/nuget/v3/index.json --name dev --username az --password ${{ env.AZURE_KEY }} --store-password-in-clear-text
        
    - name: publish
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key az --source "dev"